### PR TITLE
Allow apps to change the colour of the notch / top bar

### PR DESCRIPTION
**Pull request by DaInfLoop**
Adds a new field to the `package.json` file: `color / colour` (also added me as a contributor)

### CODE REVIEW

**Comment by codingMASTER398** [comment]
That's all fine and dandy but this request is based off the dev kit, not the full phone, dropping the cell bar, login icon, etc. from the notch.

Redo these edits on the actual phone and I'll take another look.

**Comment by DaInfLoop** [comment]
> That's all fine and dandy but this request is based off the dev kit, not the full phone, dropping the cell bar, login icon, etc. from the notch.
> 
> Redo these edits on the actual phone and I'll take another look.

Ah right forgot about that lmao

**Comment by codingMASTER398** [comment]
I would be much appreciations as you combined your two commits to kernel.js so I exactly knew what tf you were doing

**Comment by ghost** [comment]
Thank you dainf... so much

**Comment by DaInfLoop** [comment]
> Thank you dainf... so much

np

**Review by codingMASTER398 — APPROVED** [review]
Way to go amigo

**Pull request merged**
